apiVersion: v1
kind: Pod
metadata:
  namespace: learn
  name: nodeselector
  labels:
    app: nodeselector
spec:
  nodeSelector:
    node: n1
  containers:
    - name: nginx
      image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  namespace: learn
  name: nodeaffinity-service
  labels:
    app: nodeaffinity-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
---
