apiVersion: v1
kind: Pod
metadata:
  namespace: learn
  name: bacend-pp
  labels:
    app: backend-pp
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExperessions:
              - key: pos
                operator: In
                values:
                  - "1"
---
apiversion: v1
kind: Service
metadata:
  namespace: learn
  name: backend-svc
  labels:
    app: backend-svc
spec:
  selector:
    app: backend-pp
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
