apiVersion: v1
kind: Pod
metadata:
  namespace: learn
  name: pod-fe
  labels:
    app: pod-fe Inv@191245
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app: backend-pp
            topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  namespace: learn
  name: frontend-svc
  labels:
    app: frontend-svc
spec:
  selector:
    app: pod-fe
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
---
