apiVersion: v1
kind: Pod
metadata:
  namespace: learn
  name: backend
  labels:
    app: backend
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: pos
                operator: In
                values:
                  - "1"
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
---
