apiVersion: v1
kind: Pod
metadata:
  namespace: learn
  name: fe-pod
  labels:
    app: fe-pod
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: backend
          topologyKey: kubernetes.io/hostname
  containers:
    - name: fe
      image: nginx:alpine
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: learn
  name: fe-service
  labels:
    app: fe-service
spec:
  selector:
    app: fe-pod
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
---
