apiVersion: v1
kind: Pod
metadata:
  namespace: learn
  name: toleration-fe
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
  tolerations:
    - key: workload
      operator: Equal
      value: pod
      effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  namespace: learn
  name: fe-service
  labels:
    app: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
---
